### ISSUE TITLE
Add Expense Data Export Feature

### ISSUE THREAD

**Issue by neeraj542** [neeraj542/Personal-Finance-Tracker#10]
**Issue Description:**

This is to propose adding an **Expense Export** feature to our finance tracker app. Users would benefit from the ability to export their expense data in formats like CSV or Excel, making it easier to:

- Keep offline records.
- Share data with financial advisors.
- Analyze expenses in their preferred tools.
- Create backups of their financial data.

This feature would enhance the app's usability and value.

Open for all contributors!

**For better understanding:** 

<img width="256" alt="image" src="https://github.com/neeraj542/Personal-Finance-Tracker/assets/114648043/67c05fba-f49e-4867-80a1-606f0a5d7b44">

**Comment by deeksharungta** [comment]
@neeraj542 I would like to work on this issue. Could you please assign it to me?

**Comment by neeraj542** [comment]
Assigned to @deeksharungta

**Comment by neeraj542** [comment]
Hi @deeksharungta, you've done an amazing job! Please review the requested changes.

**Comment by neeraj542** [comment]
@deeksharungta are you still working on this issue?
