### ISSUE TITLE
sign up button not working 

### ISSUE THREAD

**Issue by ashish07-07** [neeraj542/Personal-Finance-Tracker#18]
the sign up buttton on the left side is not working 

https://github.com/neeraj542/Personal-Finance-Tracker/assets/83639863/f3a87725-b35b-4157-bf5a-5cd43e869c1b

**Comment by neeraj542** [comment]
Thank you @ashish07-07  for bringing this to our attention. Our system is currently undergoing maintenance, and we have added temporary links for your use. We encourage you to explore the enhanced functionality we've been working on. We are excited to receive and review your pull requests, and we'll gladly merge them if they contribute to improved performance.
